### ISSUE TITLE
Background/ Why Nuru programming language? 

### ISSUE THREAD

**Issue by Mynajobs** [AvicennaJr/Nuru#1]
Please can you include more information in the readme file to explain what triggered the establishment of this language. I am really interested to know.

 I speak Swahili, this programming language will bring big impact in my country.

**Comment by AvicennaJr** [comment]
Thank you for your request and I will add the reasoning on the README file.

In summary though, learning how to code is hard and learning it in a language you don't know is daunting. Thus, I made this so it can be easier for Swahili speakers to grasp at least the basic programming concepts.
