### ISSUE TITLE
Support for unicode chracters

### ISSUE THREAD

**Issue by iscosmos** [AvicennaJr/Nuru#35]
this language does not have support for unicode chracters
![image](https://user-images.githubusercontent.com/110777803/212559023-7c0dc158-2c52-45f0-a743-5036aeae43ad.png)

**Comment by AvicennaJr** [comment]
Thank you for pointing it out. Will fix it.

**Comment by AvicennaJr** [comment]
Already fixed. This update will be included in the next release

![fixed unicode](https://user-images.githubusercontent.com/87450618/212561559-57f9a6ca-af95-4ebb-8a6b-604b51f20a61.png)
