### ISSUE TITLE
Identifiers starting with numbers allowed, but can't be used in functions

### ISSUE THREAD

**Issue by Borwe** [AvicennaJr/Nuru#61]
### Describe the bug

![image](https://github.com/AvicennaJr/Nuru/assets/3319843/8c135508-7963-4ff6-9b91-7d4d722379ae)

As you can see I can create `4ft = "yolo"` but I can't use it after that.

### Expected Behavior

Either it shouldn't be allowed from the get go when declaring such a variable. Or if allowed then should be usable everywhere.

### Current Behavior

variable is not parsed

### Reproduction Steps

![image](https://github.com/AvicennaJr/Nuru/assets/3319843/8c135508-7963-4ff6-9b91-7d4d722379ae)

### Possible Solution

Refuse to allow variables starting with numbers.

### Nuru version

latest develop branch

### Environment details (OS name and version, etc.)

Pop_Os(Ubuntu 22.04 LTS)

**Comment by AvicennaJr** [comment]
Thank you for pointing this out

**Comment by AvicennaJr** [comment]
Thank you for pointing this out

**Comment by AvicennaJr** [comment]
Should be fixed
